## Exercício 11.2

Test the layer with a random input and check if the output shows the desired behaviour

In [1]:
import sys
sys.path.append(r"C:\Users\Álvaro Magno\Desktop\sistemas_inteligentes\sistemas_inteligentes")

In [2]:
import numpy as np
from src.si.neural_networks.layers import Dropout

# Definir a entrada de exemplo (um batch com 3 amostras, cada uma com 4 características)
input_data = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0],
    [9.0, 10.0, 11.0, 12.0]
])

# Instanciar a camada de Dropout com uma probabilidade de 50%
dropout_layer = Dropout(probability=0.5)

# Simular a fase de treinamento
training_output = dropout_layer.forward_propagation(input=input_data, training=True)
print("Saída durante o treinamento (com Dropout aplicado):")
print(training_output)

# Simular a fase de inferência (sem Dropout aplicado)
inference_output = dropout_layer.forward_propagation(input=input_data, training=False)
print("\nSaída durante a inferência (sem Dropout aplicado):")
print(inference_output)

# Simular o erro de saída durante a propagação para trás
output_error = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

# Propagação para trás (ajuste do gradiente)
backward_output = dropout_layer.backward_propagation(output_error)
print("\nErro propagado para trás:")
print(backward_output)


Saída durante o treinamento (com Dropout aplicado):
[[ 0.  0.  0.  8.]
 [ 0.  0.  0.  0.]
 [18.  0. 22. 24.]]

Saída durante a inferência (sem Dropout aplicado):
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Erro propagado para trás:
[[0.  0.  0.  0.4]
 [0.  0.  0.  0. ]
 [0.9 0.  1.1 1.2]]
