In [3]:
import pandas as pd
## Exercício 1.1
df = pd.read_csv('iris.csv')

In [5]:
## Exercício 1.2
puv = df.iloc[:, -2]
puv.shape

(150,)

In [6]:
## Exercício 1.3
ultimas_10_amostras = df.iloc[-10:, :-1]
medias = ultimas_10_amostras.mean()
print(medias)

sepal length (cm)    6.45
sepal width (cm)     3.03
petal length (cm)    5.33
petal width (cm)     2.17
dtype: float64


In [12]:
## Exercício 1.4
menores_iguais_6 = df[(df.iloc[:, :-1] <= 6).all(axis=1)]
len(menores_iguais_6)

89

In [18]:
## Exercício 1.5
diferente_i_setosa = df[(df.iloc[:, :] != 'Iris-setosa').all(axis=1)]
len(diferente_i_setosa)

150

In [ ]:
## Testes

In [5]:
import numpy as np
import pandas as pd

# Criando um DataFrame X com valores nulos
X = pd.DataFrame({
    'sepal_length': [5.1, 4.9, np.nan, 5.0, np.nan],
    'sepal_width': [3.5, np.nan, 3.1, 3.6, 3.0],
    'petal_length': [1.4, 1.4, 1.5, np.nan, 1.3],
    'petal_width': [0.2, 0.2, np.nan, 0.3, 0.2]
})

# Criando um vetor y para representar a classe
y = np.array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa'])

print("X (com valores nulos):\n", X)
print("\ny (classe):\n", y)


X (com valores nulos):
    sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          NaN           1.4          0.2
2           NaN          3.1           1.5          NaN
3           5.0          3.6           NaN          0.3
4           NaN          3.0           1.3          0.2

y (classe):
 ['Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa']


In [82]:
## dropna()
has_any_na = X.iloc[:, :].isna().any(axis=1)
indx_na = np.argwhere(has_any_na)
X = np.delete(X, indx_na, axis=0)
y = np.delete(y, indx_na, axis=0)
print(X, y)

[[5.1 3.5 1.4 0.2]] ['Iris-setosa']


In [77]:
## fillna
has_any_na = X.iloc[:, :].isna()
indx_na = np.argwhere(has_any_na)
for i in indx_na:
    if value == "mean":
        mean_feature = X.iloc[:, i[1]].mean()
        X.iloc[i[0], i[1]] = mean_feature
    elif value == "median":
        median_feature = X.iloc[:, i[1]].median()
        X.liloc[i[0], i[1]] = median_feature
    else:
        X.iloc[i[0], i[1]] = value


,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.200
1,4.9,3.3,1.4,0.200
2,5.0,3.1,1.5,0.225
3,5.0,3.6,1.4,0.300
4,5.0,3.0,1.3,0.200


In [13]:
X = X.to_numpy()
tt = np.isnan(X)
tt[:, 1]

array([False,  True, False, False, False])

In [18]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, nan, 1.4, 0.2],
       [nan, 3.1, 1.5, nan],
       [5. , 3.6, nan, 0.3],
       [nan, 3. , 1.3, 0.2]])

In [20]:
delete_X = X.copy()
delet_y = y.copy()

In [21]:
ind = [0,1]
np.delete(delete_X, ind, axis = 0)

array([[nan, 3.1, 1.5, nan],
       [5. , 3.6, nan, 0.3],
       [nan, 3. , 1.3, 0.2]])